name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'Makefile'
      - '.github/workflows/test-make.yml'
      - '.github/workflows/kics.yml'
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'Makefile'
      - '.github/workflows/test-make.yml'
      - '.github/workflows/kics.yml'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  # telemetry
  actions: read
  # ghcr push
  packages: write
  attestations: write
  id-token: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: '! github.event.pull_request.head.repo.fork'
    permissions:
      contents: write
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v8.16.0
        with:
          auto-commit: "true"
  CI:
    name: Build v${{ matrix.version }}
    needs: pre-commit
    uses: ./.github/workflows/reusable_build_and_test.yml
    strategy:
      fail-fast: false
      matrix:
        version: [25, 23, 74, 73]
    with:
      tag: ${{ github.event_name == 'pull_request' && format('pr-{0}-v{1}', github.event.pull_request.number, matrix.version) || format('{0}-v{1}', github.ref_name, matrix.version) }}
      acs_version: ${{ matrix.version }}
    secrets: inherit
