name: Build, Run and Test Docker Image

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7

      - name: Setup .netrc
        run: |
          echo "machine nexus.alfresco.com" >> ~/.netrc
          echo "login ${{ secrets.NEXUS_USERNAME }}" >> ~/.netrc
          echo "password ${{ secrets.NEXUS_PASSWORD }}" >> ~/.netrc

      - name: Fetch artifacts from nexus
        run: ${{ github.workspace }}/scripts/fetch-artifact.sh
        working-directory: ${{ github.workspace }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@5927c834f5b4fdf503fca6f4c7eccda82949e1ee # 3.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@2ad185228a349d19414702819e06df9fa4314287 # 3.4.0

      - name: Login to Docker Hub
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # 3.2.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Bake Docker images
        uses: docker/bake-action@eac74531aa56a9266bfedfe5edb6b851ce2cca2b  # v5.4.0

      - name: Show all images
        run: docker images

      - name: Verify docker-compose
        uses: Alfresco/alfresco-build-tools/.github/actions/dbp-charts/verify-compose@v5.34.0
        timeout-minutes: 10
        with:
          compose_pull: false
          compose_file_path: docker-compose/docker-compose.yml
          quay_username: ${{ secrets.QUAY_USERNAME }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}

      - uses: Alfresco/alfresco-build-tools/.github/actions/docker-dump-containers-logs@v5.34.0
