name: Test building using the make wrapper

on:
  push:
    branches:
      - main
    paths:
      - 'Makefile'
      - '.github/workflows/test-make.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'Makefile'
      - '.github/workflows/test-make.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  make-test:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/free-hosted-runner-disk-space@v5.34.0

      - name: Setup nexus authentication
        run: |
          echo "machine nexus.alfresco.com" >> ~/.netrc
          echo "login ${{ secrets.NEXUS_USERNAME }}" >> ~/.netrc
          echo "password ${{ secrets.NEXUS_PASSWORD }}" >> ~/.netrc

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Make Docker images
        id: make
        run: |
          yes | make all_ci

      - name: Check Images are loaded
        run: |
          echo -n "Checking images are loaded in local Docker Engine..."
          docker images --format "{{.Repository}}:{{.Tag}}" | grep alfresco || { echo "No Alfresco image found"; exit 1; }
